services:
  # lightrag:
  #   container_name: lightrag
  #   image: ghcr.io/hkuds/lightrag:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     tags:
  #       - ghcr.io/hkuds/lightrag:latest
  #   ports:
  #     - "${PORT:-9621}:9621"
  #   volumes:
  #     - lightrag_rag_storage:/app/data/rag_storage
  #     - lightrag_inputs:/app/data/inputs
  #     - lightrag_tiktoken:/app/data/tiktoken
  #     - ./config.ini:/app/config.ini
  #     - ./.env:/app/.env
  #   env_file:
  #     - .env
  #   environment:
  #     - TIKTOKEN_CACHE_DIR=/app/data/tiktoken
  #   restart: unless-stopped
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    volumes:
      - aperag-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=graph
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aperag"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  aperag-postgres-data: {}
  # lightrag_rag_storage:
  # lightrag_inputs:
  # lightrag_tiktoken:


